In [617]:
#Dictionary with single key-value pair
person = {
    "First_Name" : "Aditi",
    "Last_Name" : "Shaktawat",
    "Email" : "abc@email.com"
}

In [618]:
#Dictionary with multiple values in key using list
person = {
    "First_Name" : ["Aditi", "Joe", "Anu"],
    "Last_Name" : ["Shaktawat", "Sin", "Dat"],
    "Email" : ["abc@email.com", "av@email.com", "fgees@email.com"]}

In [619]:
person['Email']

['abc@email.com', 'av@email.com', 'fgees@email.com']

Creating a dataframe

In [620]:
import pandas as pd

In [621]:
df = pd.DataFrame(person)

In [622]:
df

  First_Name  Last_Name            Email
0      Aditi  Shaktawat    abc@email.com
1        Joe        Sin     av@email.com
2        Anu        Dat  fgees@email.com

Series - Return single column

In [623]:
#Accesing a singlr column in dataframe
df.Email 
#OR 
df['Email']

0      abc@email.com
1       av@email.com
2    fgees@email.com
Name: Email, dtype: object

In [624]:
#Accesing Multiple columns - dataframe
df[['First_Name', 'Email']]

  First_Name            Email
0      Aditi    abc@email.com
1        Joe     av@email.com
2        Anu  fgees@email.com

In [625]:
#Return all columns
df.columns

Index(['First_Name', 'Last_Name', 'Email'], dtype='object')

Selecting Rows

In [626]:
#Return all rows
# 1. Using iloc- integer location
df.iloc[[0,1]]

  First_Name  Last_Name          Email
0      Aditi  Shaktawat  abc@email.com
1        Joe        Sin   av@email.com

In [627]:
df.iloc[[1,2],2]  #Return 2nd column rows with index 1,2

1       av@email.com
2    fgees@email.com
Name: Email, dtype: object

In [628]:
#2. Using loc - search by labels
df.loc[[1,2], ['Email', 'First_Name']]

             Email First_Name
1     av@email.com        Joe
2  fgees@email.com        Anu

Indexing

In [629]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [630]:
df

  First_Name  Last_Name            Email
0      Aditi  Shaktawat    abc@email.com
1        Joe        Sin     av@email.com
2        Anu        Dat  fgees@email.com

In [631]:
#to set 'email' column as index
df.set_index( 'Email',inplace=True)

In [632]:
df

                First_Name  Last_Name
Email
abc@email.com        Aditi  Shaktawat
av@email.com           Joe        Sin
fgees@email.com        Anu        Dat

In [633]:
#Finding rows using 'email' as label
df.loc[ 'av@email.com']

First_Name    Joe
Last_Name     Sin
Name: av@email.com, dtype: object

In [634]:
#  df.loc[0]   --will give error as int labels no longer acting as labels

In [635]:
# return a specific column for the speciified row
df.loc['av@email.com','First_Name']

'Joe'

In [636]:
#Reset index
df.reset_index(inplace=True)
df

             Email First_Name  Last_Name
0    abc@email.com      Aditi  Shaktawat
1     av@email.com        Joe        Sin
2  fgees@email.com        Anu        Dat

Filtering

In [637]:
#1st way
filt = df['Last_Name'] == 'Shaktawat'   #Returns a series of true false booleans

In [638]:
# df[filt]
# or
# df.loc[filt]

In [639]:
df.loc[filt, 'Email']   #return email where last name is 'Shaktawat'

0    abc@email.com
Name: Email, dtype: object

In [640]:
# 2nd way
df[df['Last_Name'] == 'Shaktawat']

           Email First_Name  Last_Name
0  abc@email.com      Aditi  Shaktawat

In [641]:
# AND filter
df[(df['First_Name'] == 'Aditi') & (df['Email'] == 'abc@email.com')]

           Email First_Name  Last_Name
0  abc@email.com      Aditi  Shaktawat

In [642]:
filt = (df['Last_Name'] == 'Shaktawat') & (df['Email'] == 'abc@email.com')
df.loc[filt]

           Email First_Name  Last_Name
0  abc@email.com      Aditi  Shaktawat

In [643]:
# OR condition
df[(df['Last_Name'] == 'Sin') | (df['Email'] == 'abc@email.com')]

           Email First_Name  Last_Name
0  abc@email.com      Aditi  Shaktawat
1   av@email.com        Joe        Sin

In [644]:
filt = (df['Last_Name'] == 'Sin') | (df['Email'] == 'abc@email.com')
df.loc[filt, 'First_Name']

0    Aditi
1      Joe
Name: First_Name, dtype: object

In [645]:
# NOT 
df.loc[~filt]   #opposite of filtering condition

             Email First_Name Last_Name
2  fgees@email.com        Anu       Dat

Alteriing Columns

In [646]:
df.columns

Index(['Email', 'First_Name', 'Last_Name'], dtype='object')

In [647]:
# 1. changing column names using list
df.columns = ['First', 'Last', 'email']
df

             First   Last      email
0    abc@email.com  Aditi  Shaktawat
1     av@email.com    Joe        Sin
2  fgees@email.com    Anu        Dat

In [648]:
# 2. Renaming few column names - using dictionary
df.rename(columns= {'First' :'First Name', 'email' : 'Email'}, inplace= True)

In [649]:
df   # need to add inplace = true for rename

        First Name   Last      Email
0    abc@email.com  Aditi  Shaktawat
1     av@email.com    Joe        Sin
2  fgees@email.com    Anu        Dat

In [650]:
#Changing CASE of columns   - list comprehension
df.columns = [x.upper() for x in df.columns]
df

        FIRST NAME   LAST      EMAIL
0    abc@email.com  Aditi  Shaktawat
1     av@email.com    Joe        Sin
2  fgees@email.com    Anu        Dat

In [651]:
df.columns = [x.lower() for x in df.columns]
df

        first name   last      email
0    abc@email.com  Aditi  Shaktawat
1     av@email.com    Joe        Sin
2  fgees@email.com    Anu        Dat

In [652]:
# replacing values/ spaces in columns
df.columns = df.columns.str.replace(' ', '_')
df

        first_name   last      email
0    abc@email.com  Aditi  Shaktawat
1     av@email.com    Joe        Sin
2  fgees@email.com    Anu        Dat

Updating Row values

In [653]:
df.loc[2]

first_name    fgees@email.com
last                      Anu
email                     Dat
Name: 2, dtype: object

In [654]:
#updating Single value
# 1. directly updating all the values for a single row

df.loc[2] = ['Vin', 'Jain', 'vin@gmail.com']
df

      first_name   last          email
0  abc@email.com  Aditi      Shaktawat
1   av@email.com    Joe            Sin
2            Vin   Jain  vin@gmail.com

In [655]:
# 2. Updating few particular values for a single row 
df.loc[2, ['first_name','email']] =[ 'Vinamra' , 'vinad@gmail.com']
df

      first_name   last            email
0  abc@email.com  Aditi        Shaktawat
1   av@email.com    Joe              Sin
2        Vinamra   Jain  vinad@gmail.com

In [656]:
# 3. update single value
df.loc[ 2, 'email'] = 'vinlovad@email.com'
df

      first_name   last               email
0  abc@email.com  Aditi           Shaktawat
1   av@email.com    Joe                 Sin
2        Vinamra   Jain  vinlovad@email.com

Updating multiple rows values

In [657]:
df['first_name'] = df['first_name'].str.lower()
df

      first_name   last               email
0  abc@email.com  Aditi           Shaktawat
1   av@email.com    Joe                 Sin
2        vinamra   Jain  vinlovad@email.com

APPLY

In [658]:
# 1. APPLY with series - apply changes to each value of series

df['email'].apply(len)

0     9
1     3
2    18
Name: email, dtype: int64

In [659]:
#cretaing a func for converting the case of email
def email_upper(email):
    return email.upper()
df['email'].apply(email_upper)
#apply to the column
df['email'] = df['email'].apply(email_upper)

In [660]:
df

      first_name   last               email
0  abc@email.com  Aditi           SHAKTAWAT
1   av@email.com    Joe                 SIN
2        vinamra   Jain  VINLOVAD@EMAIL.COM

In [661]:
# Or using LAMBDA func
df['email'] = df['email'].apply(lambda x: x.lower())
df

      first_name   last               email
0  abc@email.com  Aditi           shaktawat
1   av@email.com    Joe                 sin
2        vinamra   Jain  vinlovad@email.com

In [662]:
# 2. Apply with dataframe - apply func to every series in dataframe
df.apply(len)

first_name    3
last          3
email         3
dtype: int64

In [663]:
df.apply(pd.Series.max)

first_name               vinamra
last                         Joe
email         vinlovad@email.com
dtype: object

In [664]:
df.apply(lambda x: x.min())

first_name    abc@email.com
last                  Aditi
email             shaktawat
dtype: object

APPLY MAP

In [665]:
# Works in every individual value od dataframe
#does not work on series
df.applymap(len)

C:\Users\aditi\AppData\Local\Temp\ipykernel_14512\291979854.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

   first_name  last  email
0          13     5      9
1          12     3      3
2           7     4     18

In [666]:
df.applymap(str.lower)

C:\Users\aditi\AppData\Local\Temp\ipykernel_14512\357608748.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(str.lower)

      first_name   last               email
0  abc@email.com  aditi           shaktawat
1   av@email.com    joe                 sin
2        vinamra   jain  vinlovad@email.com

MAP

In [667]:
# works only on series
# use to substite each value in series with something else
df['first_name'].map({'aditi' : 'ad', 'vinamra' :'vin'})   # if value not changed, returns NAN

0    NaN
1    NaN
2    vin
Name: first_name, dtype: object

REPLACE

In [668]:
df

      first_name   last               email
0  abc@email.com  Aditi           shaktawat
1   av@email.com    Joe                 sin
2        vinamra   Jain  vinlovad@email.com

In [669]:
#Wont return NAN for the values which are not changed
df['first_name']= df['first_name'].replace({'aditi' : 'ad', 'vinamra' :'vin'})
df

      first_name   last               email
0  abc@email.com  Aditi           shaktawat
1   av@email.com    Joe                 sin
2            vin   Jain  vinlovad@email.com

Adding new columns

In [670]:
#Creating a new column by combining 2 column values
df['Full_name'] = df['first_name'] + ' ' + df['last']
df['Salary'] = [20000,3000,65346]
df

      first_name   last               email            Full_name  Salary
0  abc@email.com  Aditi           shaktawat  abc@email.com Aditi   20000
1   av@email.com    Joe                 sin     av@email.com Joe    3000
2            vin   Jain  vinlovad@email.com             vin Jain   65346

Removing Column

In [671]:
df.drop(columns= ['first_name', 'last'], inplace=True)

In [672]:
df

                email            Full_name  Salary
0           shaktawat  abc@email.com Aditi   20000
1                 sin     av@email.com Joe    3000
2  vinlovad@email.com             vin Jain   65346

Splitting Columns

In [673]:
df['Full_name'].str.split(' ',expand=True)

               0      1
0  abc@email.com  Aditi
1   av@email.com    Joe
2            vin   Jain

In [674]:
#naming 2 cloumns which are split
df[['First_Name', 'Last_Name']] = df['Full_name'].str.split(' ',expand= True)

In [675]:
df

                email            Full_name  Salary     First_Name Last_Name
0           shaktawat  abc@email.com Aditi   20000  abc@email.com     Aditi
1                 sin     av@email.com Joe    3000   av@email.com       Joe
2  vinlovad@email.com             vin Jain   65346            vin      Jain

Adding new rows

In [676]:
new_row = {
    'email' : ['tony@gmail.com', 'steeve@gmail.com', 'steeve@gmail.com'],
    'Full_name': ['Tony Stark','Steeve Jobs','deep Sin'],
    'Salary' : [980,225000,34000]
}
df2 =pd.DataFrame(new_row)
df = pd.concat([df,df2], ignore_index=True)
df

                email            Full_name  Salary     First_Name Last_Name
0           shaktawat  abc@email.com Aditi   20000  abc@email.com     Aditi
1                 sin     av@email.com Joe    3000   av@email.com       Joe
2  vinlovad@email.com             vin Jain   65346            vin      Jain
3      tony@gmail.com           Tony Stark     980            NaN       NaN
4    steeve@gmail.com          Steeve Jobs  225000            NaN       NaN
5    steeve@gmail.com             deep Sin   34000            NaN       NaN

Removing rows

In [677]:
#Directly using index value
df.drop(index=4, inplace=True)
df

                email            Full_name  Salary     First_Name Last_Name
0           shaktawat  abc@email.com Aditi   20000  abc@email.com     Aditi
1                 sin     av@email.com Joe    3000   av@email.com       Joe
2  vinlovad@email.com             vin Jain   65346            vin      Jain
3      tony@gmail.com           Tony Stark     980            NaN       NaN
5    steeve@gmail.com             deep Sin   34000            NaN       NaN

In [678]:
#Remove row where email = steeve@gmail.com
# 1 way
# df.drop(index= df[df['email'] == 'steeve@gmail.com'].index)

In [679]:
# 2nd way
filt = (df['email'] == 'tony@gmail.com')
df.drop(index=df[filt].index)

                email            Full_name  Salary     First_Name Last_Name
0           shaktawat  abc@email.com Aditi   20000  abc@email.com     Aditi
1                 sin     av@email.com Joe    3000   av@email.com       Joe
2  vinlovad@email.com             vin Jain   65346            vin      Jain
5    steeve@gmail.com             deep Sin   34000            NaN       NaN

Sorting columns data

In [680]:
#sort by 1 column
df.sort_values(by='email', ascending=False)

                email            Full_name  Salary     First_Name Last_Name
2  vinlovad@email.com             vin Jain   65346            vin      Jain
3      tony@gmail.com           Tony Stark     980            NaN       NaN
5    steeve@gmail.com             deep Sin   34000            NaN       NaN
1                 sin     av@email.com Joe    3000   av@email.com       Joe
0           shaktawat  abc@email.com Aditi   20000  abc@email.com     Aditi

In [681]:
# sort by 2 columns( 1st column value same)
df.sort_values(by=['email','Full_name'], ascending=False, inplace=True)

In [682]:
df

                email            Full_name  Salary     First_Name Last_Name
2  vinlovad@email.com             vin Jain   65346            vin      Jain
3      tony@gmail.com           Tony Stark     980            NaN       NaN
5    steeve@gmail.com             deep Sin   34000            NaN       NaN
1                 sin     av@email.com Joe    3000   av@email.com       Joe
0           shaktawat  abc@email.com Aditi   20000  abc@email.com     Aditi

In [683]:
# sort 1 column by desc and another by asc( in matching conditions)
df.sort_values(by=['email','Full_name'], ascending=[False,True])

                email            Full_name  Salary     First_Name Last_Name
2  vinlovad@email.com             vin Jain   65346            vin      Jain
3      tony@gmail.com           Tony Stark     980            NaN       NaN
5    steeve@gmail.com             deep Sin   34000            NaN       NaN
1                 sin     av@email.com Joe    3000   av@email.com       Joe
0           shaktawat  abc@email.com Aditi   20000  abc@email.com     Aditi

In [684]:
#SORTING INDEXES 
df.sort_index(inplace=True)   #return to original data

In [685]:
#Sorting series objects
df['Last_Name'].sort_values()

0    Aditi
2     Jain
1      Joe
3      NaN
5      NaN
Name: Last_Name, dtype: object

In [686]:
df

                email            Full_name  Salary     First_Name Last_Name
0           shaktawat  abc@email.com Aditi   20000  abc@email.com     Aditi
1                 sin     av@email.com Joe    3000   av@email.com       Joe
2  vinlovad@email.com             vin Jain   65346            vin      Jain
3      tony@gmail.com           Tony Stark     980            NaN       NaN
5    steeve@gmail.com             deep Sin   34000            NaN       NaN

In [ ]:
# 3 largest salary
df['Salary'].nlargest(3)

2    65346
5    34000
0    20000
Name: Salary, dtype: int64

In [689]:
#all details of 10 largest salary
df.nlargest(4, 'Salary')

                email            Full_name  Salary     First_Name Last_Name
2  vinlovad@email.com             vin Jain   65346            vin      Jain
5    steeve@gmail.com             deep Sin   34000            NaN       NaN
0           shaktawat  abc@email.com Aditi   20000  abc@email.com     Aditi
1                 sin     av@email.com Joe    3000   av@email.com       Joe

In [690]:
# smallest 2 salary
df.nsmallest(2, 'Salary')

            email         Full_name  Salary    First_Name Last_Name
3  tony@gmail.com        Tony Stark     980           NaN       NaN
1             sin  av@email.com Joe    3000  av@email.com       Joe