In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('survey_dataset.csv')

In [3]:
pd.set_option('display.max_columns',114)
pd.set_option('display.max_rows',114)

In [4]:
df.shape

(65437, 114)

In [5]:
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [6]:
df.select_dtypes(include='number').columns

Index(['ResponseId', 'CompTotal', 'WorkExp', 'JobSatPoints_1',
       'JobSatPoints_4', 'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7',
       'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10',
       'JobSatPoints_11', 'ConvertedCompYearly', 'JobSat'],
      dtype='object')

Aggregating data

In [7]:
# findian salary of data
df['ConvertedCompYearly'].unique()

array([    nan,   7322.,  30074., ...,  15637.,   9711., 116844.],
      shape=(6114,))

In [8]:
#Median salary
df['ConvertedCompYearly'].median()

65000.0

In [9]:
df.median(numeric_only= True)

ResponseId              32719.0
CompTotal              110000.0
WorkExp                     9.0
JobSatPoints_1             10.0
JobSatPoints_4              0.0
JobSatPoints_5              0.0
JobSatPoints_6             20.0
JobSatPoints_7             15.0
JobSatPoints_8             10.0
JobSatPoints_9              5.0
JobSatPoints_10             0.0
JobSatPoints_11             0.0
ConvertedCompYearly     65000.0
JobSat                      7.0
dtype: float64

In [10]:
# To see about the overall statistics analysis of data

df.describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

In [11]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       ...
       'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9',
       'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase',
       'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=114)

In [12]:
df['Country'].count()    #counts non null values rows

np.int64(58930)

In [13]:
df['Country'].value_counts()      #count no. of unique rows in data

Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
                                                        ...
Central African Republic                                    1
Equatorial Guinea                                           1
Niger                                                       1
Guinea                                                      1
Solomon Islands                                             1
Name: count, Length: 185, dtype: int64

Grouping data

<!--  GROUP BY = 
    [split data] + [apply fun] + [combine results] -->

In [14]:
# Find Employement details for each country
# 1. Split data country wise
Country_grp = df.groupby(['Country'])

In [15]:
Country_grp.get_group('India')

C:\Users\aditi\AppData\Local\Temp\ipykernel_19112\2972040018.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  Country_grp.get_group('India')

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
17,18,I am a developer by profession,18-24 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Coding sessions (live or recorded);How-t...,NaN,6,3,"Developer, front-end",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,NaN,NaN,NaN,Amazon Web Services (AWS);Digital Ocean;Fireba...,NaN,NaN,jQuery;Next.js;React,Next.js;React,Next.js;React,NaN,NaN,NaN,React Native,OpenGL;React Native,React Native,Docker;npm;Vite;Yarn,Docker;pnpm;Vite,Docker;Vite,VSCodium,VSCodium,VSCodium,Windows,Windows,Azure Devops,Azure Devops,Azure Devops,Google Meet;Microsoft Teams;Telegram;Whatsapp,Google Meet;Microsoft Teams,Google Meet;Microsoft Teams,ChatGPT,GitHub Copilot;Google Gemini,NaN,Stack Overflow;Stack Exchange,Less than once per month or monthly,Yes,Less than once per month or monthly,Quickly finding code solutions,Neutral,"No, but I plan to soon",Favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,Replacing jobs without options for new employm...,Lack of executive buy-in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
58,59,"I am not primarily a developer, but I write co...",18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;Coding sessions (live or record...,NaN,4,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C++;HTML/CSS;JavaScript;Python;SQL,C++;HTML/CSS;Python,C++;HTML/CSS;Python,SQLite,NaN,NaN,NaN,NaN,NaN,Django;Node.js,Django,Django,Arduino,Arduino,Arduino,NaN,NaN,NaN,npm,NaN,NaN,Code::Blocks;PyCharm;Visual Studio Code,Code::Blocks;Visual Studio Code,Code::Blocks;Visual Studio Code,Android;Ubuntu;Windows,Windows,NaN,NaN,NaN,Discord;Telegram;Whatsapp,Whatsapp,Whatsapp,ChatGPT,GitHub Copilot;Google Gemini,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,Neutral,Yes,Favorable,Increase productivity;Greater efficiency;Make ...,Somewhat trust,Neither good or bad at handling complex tasks,Debugging and getting help;Search for answers,NaN,NaN,NaN,Search for answers,Debugging and getting help,NaN,NaN,No,Circulating misinformation or disinformation;M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
75,76,I am learning to code,25-34 years old,"Not employed, but looking for work",NaN,Apples,NaN,Some college/university study without earning ...,Online Courses or Certification;Coding Bootcamp,NaN,NaN,4,NaN,Designer,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,HTML/CSS;JavaScript,Dart;Kotlin;Swift,NaN,MongoDB,NaN,NaN,Firebase;Heroku;VMware,Digital Ocean,NaN,Node.js;React,NaN,NaN,NaN,NaN,NaN,Flutter;Ionic;React Native,NaN,NaN,npm,NaN,NaN,Android Studio;IntelliJ IDEA;Notepad++;Sublime...,NaN,NaN,Android;Ubuntu;Windows,NaN,Asana;Clickup;Miro;Monday.com,Notion;Stack Overflow for Teams,NaN,Skype;Slack;Whatsapp;Zoom,Discord;Google Chat,NaN,Google Gemini,NaN,NaN,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,Quickly finding code solutions;Finding reliabl...,Neutral,"No, but I plan to soon",Favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Replacing jobs without options for new employm...,Don’t trust the output or answers;Not everyone...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
89,90,I am learning to code,25-34 years old,"Employed, full-time",In-person,Apples,Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","School (i.e., University, College, etc);Online...",NaN,NaN,2,NaN,Security professional,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;SQL;Visual ...,HTML/CSS;Java;JavaScript;PHP;SQL;Visual Basic ...,HTML/CSS;Java;JavaScript;PHP;SQL;Visual Basic ...,Elasticsearch;MySQL;Oracle,Elasticsearch;MySQL;Oracle,Elasticsearch;MySQL;Oracle,Managed Hosting;VMware,NaN,NaN,ASP.NET;CodeIgniter;Node.js;WordPress,CodeIgniter;Node.js,CodeIgniter;Node.js,Rasberry Pi,Rasberry Pi,Rasberry Pi,NumPy,NaN,NaN,npm,NaN,NaN,Nano;Netbeans;Notepad++;Sublime Text;Vim;Visua...,Nano;Notepad++;Visual Studio Code,Nano;Notepad++;Visual Studio Code,Debian;Ubuntu;Windows;Windows Subsystem for Li...,Debian;Ubuntu;Windows;Windows Subsystem for Li...,Stack Overflow for Teams,NaN,NaN,Cisco Webex Teams;Discord;Google Meet;Microsof...,Discord;Google Meet;Microsoft Teams;Telegram;W...,Discord;Google Meet;Microsoft Teams;Telegram;W...,ChatGPT;Snyk Code,ChatGPT;Snyk Code,ChatGPT;Snyk Code,Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,Finding reliable guidance from community-vette...,"Yes, definitely","No, but I plan to soon",Favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;R...,Not everyone uses them,Yes,Individual contributor,3.0,Agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Neither agree nor disagree,Agree,Agree,Never,1-2 times a week,Never,60-120 minutes a day,Less than 15 minutes a day,None of these,Observability tools;Knowledge sharing community,Hybrid (on-prem and cloud),AI-powered search (free),Higher Education,80.0,90.0,90.0,50.0,70.0,50.0,50.0,50.0,80.0,Appropriate in length,Easy,NaN,8.0
96,97,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",NaN,NaN,11,7,"Developer, mobile",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,Bash/Shell (all shells);C#;JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.NET (5+) ;.NET MAUI,NaN,NaN,NuGet,NaN,NaN,Visual Studio;Visual Studio Code;Xcode,Rider,NaN,Android;Windows,Android;iOS;MacOS;Windows,Azure Devops,NaN,NaN,Microsoft Teams,NaN,NaN,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot;Google Gemini;Meta AI,ChatGPT;GitHub Copilot,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"Yes, somewhat",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Documenting code;Search for answe...,Learning about a codebase;Project planning;Deb...,NaN,Generating content or synthetic data,NaN,Writing code;Documenting code;Search for answers,NaN,NaN,Yes,Biased results that do not represent diverse v...,"AI tools lack context of codebase, internal a...",Yes,Individual contributor,7.0,Agree,Neither agree nor disagree,Disagree,Agree,Neither agree nor disagree,Agree,Agree,Agree,Strongly disagree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,Amount of technical debt;Tracking my work;Show...,DevOps function;Developer portal or other cent...,Cloud only (single or multi-cloud),A coworker,Software Development,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Too long,Easy,NaN,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65339,65340,"I am not primarily a developer, but I write co...",18-24 years old,"Student, full-time",NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Social Media;How-to vi...,API document(s) and/or SDK document(s),4,2,"Developer, mobile",NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,C;C#;C++;Go;HTML/CSS;JavaScript;Objective-C;Py...,NaN,NaN,Cassandra;Firebase Realtime Database;MariaDB;M...,NaN,NaN,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,Django;Flask;Next.js;Node.js;React,NaN,NaN,Arduino;Rasberry Pi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Daily or almost daily,No,NaN,Quickly finding code solutions;Finding reliabl...,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65383,65384,I am learning to code,18-24 years old,"Not employed, but looking for work",NaN,Apples,NaN,Some college/university study without earning ...,"School (i.e., University, College, etc)",NaN,NaN,9,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Exchange,Less than once per month or monthly,Yes,I have never participated in Q&A on Stack Over...,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65413,65414,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Social Media;How-to videos;Video-based Online ...,NaN,3,NaN,Student,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,No,NaN,Quickly finding code solutions,"No, not at all",Yes,Unsure,Increase productivity;Speed up learning;Make w...,Somewhat trust,Bad at handling complex tasks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65415,65416,I code primarily as a hobby,35-44 years old,I prefer not to say,NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Stack Overflow;Social Media;Video-based ...,NaN,4,NaN,System administrator,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Engage with com...,"Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65428,65429,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Other online ...,Technical documentation;Books;Interactive tuto...,API document(s) and/or SDK document(s);User gu...,4,7,"Developer, back-end","1,000 to 4,999 employees",I have some influence,Start a free trial;Ask developers I know/work ...,NaN,Integrated developer community;Frequent update...,India,INR\tIndian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,No,NaN,Quickly finding code solutions;Finding reliabl...,Neutral,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# 2. Apply fun
Country_grp['Employment'].value_counts()

Country      Employment
Afghanistan  Employed, full-time                                                                                           22
             Independent contractor, freelancer, or self-employed                                                           8
             I prefer not to say                                                                                            6
             Student, full-time                                                                                             6
             Employed, full-time;Independent contractor, freelancer, or self-employed                                       2
                                                                                                                           ..
Zimbabwe     I prefer not to say                                                                                            1
             Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time                    1
             Not employed, but looking for work                                                                             1
             Retired                                                                                                        1
             Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed     1
Name: count, Length: 2601, dtype: int64

In [17]:
# 3. Combine results to check for any 1 county
Country_grp['Employment'].value_counts().loc['India']

Employment
Employed, full-time                                                                                                                                                      2461
Student, full-time                                                                                                                                                        553
Not employed, but looking for work                                                                                                                                        251
Independent contractor, freelancer, or self-employed                                                                                                                      223
Employed, full-time;Independent contractor, freelancer, or self-employed                                                                                                  156
Student, full-time;Not employed, but looking for work                                                                                                                      92
Student, part-time                                                                                                                                                         62
Student, full-time;Employed, part-time                                                                                                                                     41
I prefer not to say                                                                                                                                                        40
Not employed, and not looking for work                                                                                                                                     35
Student, full-time;Independent contractor, freelancer, or self-employed                                                                                                    35
Employed, part-time                                                                                                                                                        32
Not employed, but looking for work;Independent contractor, freelancer, or self-employed                                                                                    29
Employed, full-time;Student, full-time                                                                                                                                     28
Employed, full-time;Student, part-time                                                                                                                                     28
Student, full-time;Not employed, and not looking for work                                                                                                                  20
Independent contractor, freelancer, or self-employed;Employed, part-time                                                                                                   18
Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time                                                                               15
Employed, full-time;Employed, part-time                                                                                                                                    10
Student, full-time;Student, part-time                                                                                                                                       9
Not employed, but looking for work;Student, part-time                                                                                                                       8
Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed                                                                  8
Employed, full-time;Not employed, but looking for work                                                                                                                      7
Independent contractor, freelancer, or self-employed;Student, part-time                                                                                                     7
Retired                                                                                                                                                                     7
Student, part-time;Employed, part-time                                                                                                                                      6
Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed                                                                                 5
Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time                                                                                 4
Not employed, and not looking for work;Student, part-time                                                                                                                   4
Not employed, but looking for work;Not employed, and not looking for work                                                                                                   3
Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time                                                                                 3
Student, full-time;Not employed, but looking for work;Employed, part-time                                                                                                   3
Student, full-time;Not employed, but looking for work;Student, part-time                                                                                                    3
Employed, full-time;Student, full-time;Employed, part-time                                                                                                                  2
Independent contractor, freelancer, or self-employed;Not employed, and not looking for work                                                                                 2
Independent contractor, freelancer, or self-employed;Retired                                                                                                                2
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time                                                                  2
Student, full-time;Not employed, and not looking for work;Student, part-time                                                                                                2
Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time                                         1
Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time                                          1
Employed, full-time;Student, full-time;Not employed, but looking for work                                                                                                   1
Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time       1
Employed, full-time;Student, part-time;Employed, part-time                                                                                                                  1
Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time                                                                                 1
Not employed, and not looking for work;Employed, part-time                                                                                                                  1
Not employed, but looking for work;Employed, part-time                                                                                                                      1
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time                                                                 1
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Retired                                      1
Not employed, but looking for work;Not employed, and not looking for work;Student, part-time                                                                                1
Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time                                                                                  1
Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time                                                              1
Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time                                              1
Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time                                               1
Name: count, dtype: int64

In [18]:
# to see the data in percentage
Country_grp['Employment'].value_counts(normalize= True).loc['Japan']

Employment
Employed, full-time                                                                                           0.715278
Independent contractor, freelancer, or self-employed                                                          0.100694
Employed, full-time;Independent contractor, freelancer, or self-employed                                      0.062500
Student, full-time                                                                                            0.041667
Student, full-time;Employed, part-time                                                                        0.013889
I prefer not to say                                                                                           0.010417
Not employed, but looking for work                                                                            0.010417
Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time                  0.006944
Not employed, and not looking for work                                                                        0.006944
Student, part-time                                                                                            0.006944
Employed, full-time;Employed, part-time                                                                       0.003472
Employed, part-time                                                                                           0.003472
Not employed, and not looking for work;Retired                                                                0.003472
Not employed, but looking for work;Independent contractor, freelancer, or self-employed                       0.003472
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time    0.003472
Retired                                                                                                       0.003472
Student, full-time;Not employed, but looking for work                                                         0.003472
Name: proportion, dtype: float64

In [19]:
# To check the employement result for any 1 country - FILTER can also be used
filt = df['Country'] == 'Japan'
df.loc[filt]
df.loc[filt,'Employment'].value_counts(normalize= True)

# But fro all the countries - use GROUP BY

Employment
Employed, full-time                                                                                           0.715278
Independent contractor, freelancer, or self-employed                                                          0.100694
Employed, full-time;Independent contractor, freelancer, or self-employed                                      0.062500
Student, full-time                                                                                            0.041667
Student, full-time;Employed, part-time                                                                        0.013889
Not employed, but looking for work                                                                            0.010417
I prefer not to say                                                                                           0.010417
Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time                  0.006944
Not employed, and not looking for work                                                                        0.006944
Student, part-time                                                                                            0.006944
Employed, full-time;Employed, part-time                                                                       0.003472
Not employed, but looking for work;Independent contractor, freelancer, or self-employed                       0.003472
Retired                                                                                                       0.003472
Student, full-time;Not employed, but looking for work                                                         0.003472
Not employed, and not looking for work;Retired                                                                0.003472
Employed, part-time                                                                                           0.003472
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time    0.003472
Name: proportion, dtype: float64

In [20]:
# To check age percntageof people participated in survey based on conutry

count_grp = df.groupby(['Country'])
count_grp['Age'].value_counts( normalize= True).head(50)

# OR 
#  df.groupby(['Country'])['CompTotal'].value_counts()

Country              Age
Afghanistan          25-34 years old       0.446429
                     18-24 years old       0.232143
                     35-44 years old       0.142857
                     Prefer not to say     0.053571
                     Under 18 years old    0.053571
                     65 years or older     0.035714
                     45-54 years old       0.017857
                     55-64 years old       0.017857
Albania              18-24 years old       0.408163
                     25-34 years old       0.326531
                     35-44 years old       0.163265
                     45-54 years old       0.061224
                     Prefer not to say     0.020408
                     Under 18 years old    0.020408
Algeria              25-34 years old       0.402597
                     18-24 years old       0.389610
                     35-44 years old       0.077922
                     Under 18 years old    0.077922
                     45-54 years old       0.025974
                     55-64 years old       0.012987
                     65 years or older     0.012987
Andorra              18-24 years old       0.400000
                     25-34 years old       0.133333
                     35-44 years old       0.133333
                     45-54 years old       0.133333
                     Under 18 years old    0.133333
                     55-64 years old       0.066667
Angola               18-24 years old       0.450000
                     25-34 years old       0.400000
                     45-54 years old       0.050000
                     55-64 years old       0.050000
                     Prefer not to say     0.050000
Antigua and Barbuda  25-34 years old       0.200000
                     35-44 years old       0.200000
                     55-64 years old       0.200000
                     65 years or older     0.200000
                     Under 18 years old    0.200000
Argentina            35-44 years old       0.315942
                     25-34 years old       0.307246
                     18-24 years old       0.156522
                     45-54 years old       0.130435
                     55-64 years old       0.049275
                     65 years or older     0.023188
                     Under 18 years old    0.017391
Armenia              25-34 years old       0.448276
                     18-24 years old       0.241379
                     35-44 years old       0.172414
                     45-54 years old       0.068966
                     55-64 years old       0.017241
                     65 years or older     0.017241
Name: proportion, dtype: float64

Median salary for each country

In [48]:
median_salary = count_grp['CompTotal'].median()
median_salary

Country
Afghanistan                                 26000.0
Albania                                     90000.0
Algeria                                    600000.0
Andorra                                     40000.0
Angola                                    1350000.0
                                           ...
Venezuela, Bolivarian Republic of...        12600.0
Viet Nam                                202000000.0
Yemen                                       50000.0
Zambia                                      49200.0
Zimbabwe                                    18000.0
Name: CompTotal, Length: 185, dtype: float64

In [50]:
mean_sal = count_grp['CompTotal'].mean()
mean_sal

Country
Afghanistan                             4.166667e+51
Albania                                 1.493638e+06
Algeria                                 7.415032e+05
Andorra                                 9.400000e+04
Angola                                  3.412757e+07
                                            ...
Venezuela, Bolivarian Republic of...    2.091343e+04
Viet Nam                                2.942487e+08
Yemen                                   1.295200e+06
Zambia                                  3.097925e+05
Zimbabwe                                3.046000e+04
Name: CompTotal, Length: 185, dtype: float64

In [51]:
salary_df = pd.concat([median_salary, mean_sal],axis='columns')
salary_df

                                        CompTotal     CompTotal
Country
Afghanistan                               26000.0  4.166667e+51
Albania                                   90000.0  1.493638e+06
Algeria                                  600000.0  7.415032e+05
Andorra                                   40000.0  9.400000e+04
Angola                                  1350000.0  3.412757e+07
...                                           ...           ...
Venezuela, Bolivarian Republic of...      12600.0  2.091343e+04
Viet Nam                              202000000.0  2.942487e+08
Yemen                                     50000.0  1.295200e+06
Zambia                                    49200.0  3.097925e+05
Zimbabwe                                  18000.0  3.046000e+04

[185 rows x 2 columns]

In [55]:
salary_df.columns= ['Median_Salary','Mean_Salary']
salary_df

                                      Median_Salary   Mean_Salary
Country
Afghanistan                                 26000.0  4.166667e+51
Albania                                     90000.0  1.493638e+06
Algeria                                    600000.0  7.415032e+05
Andorra                                     40000.0  9.400000e+04
Angola                                    1350000.0  3.412757e+07
...                                             ...           ...
Venezuela, Bolivarian Republic of...        12600.0  2.091343e+04
Viet Nam                                202000000.0  2.942487e+08
Yemen                                       50000.0  1.295200e+06
Zambia                                      49200.0  3.097925e+05
Zimbabwe                                    18000.0  3.046000e+04

[185 rows x 2 columns]

In [22]:
# Median salry in germany
count_grp['CompTotal'].median().loc['Germany']

np.float64(69000.0)

Median and mean salary for 'India'

In [23]:
# using agg fun
count_grp['CompTotal'].agg(['median', 'mean']).loc['India']

median    1.300000e+06
mean      4.892193e+10
Name: India, dtype: float64

How many people in each country know how to use pyhton

In [24]:
# using filter
filt = df['LanguageHaveWorkedWith'].str.contains('Python',na= False)

In [25]:
df.loc[filt, 'Country'].value_counts()

Country
United States of America                                6251
Germany                                                 2647
India                                                   2128
United Kingdom of Great Britain and Northern Ireland    1638
France                                                  1187
                                                        ...
Samoa                                                      1
Niger                                                      1
Dominica                                                   1
Suriname                                                   1
Barbados                                                   1
Name: count, Length: 173, dtype: int64

Pyhton developers in 'India'

In [26]:
# Using FILTER
filt = df['Country'] == 'India'
df.loc[filt, 'LanguageHaveWorkedWith'].str.contains('Python').value_counts()

LanguageHaveWorkedWith
True     2128
False    1930
Name: count, dtype: int64

In [27]:
df.loc[filt, 'LanguageHaveWorkedWith'].str.contains('Python').sum()

2128

In [28]:
# Using group by
Country_grp['LanguageHaveWorkedWith'].str.contains('Python').sum()  # give errors

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [ ]:
#using apply in group by
Country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              26
Albania                                  10
Algeria                                  37
Andorra                                   8
Angola                                    9
                                       ...
Venezuela, Bolivarian Republic of...     25
Viet Nam                                138
Yemen                                    10
Zambia                                    8
Zimbabwe                                 17
Name: LanguageHaveWorkedWith, Length: 185, dtype: int64

What % of people from each country knows python

In [29]:
total_respondents= df['Country'].value_counts()
total_respondents

Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
                                                        ...
Central African Republic                                    1
Equatorial Guinea                                           1
Niger                                                       1
Guinea                                                      1
Solomon Islands                                             1
Name: count, Length: 185, dtype: int64

In [30]:

python_respondants = df.groupby(['Country'])['LanguageHaveWorkedWith'].apply( lambda x: x.str.contains('Python').sum())
python_respondants

Country
Afghanistan                              26
Albania                                  10
Algeria                                  37
Andorra                                   8
Angola                                    9
                                       ...
Venezuela, Bolivarian Republic of...     25
Viet Nam                                138
Yemen                                    10
Zambia                                    8
Zimbabwe                                 17
Name: LanguageHaveWorkedWith, Length: 185, dtype: int64

In [31]:
#creating new dataframe for these 2 columns
python_df = pd.concat([total_respondents, python_respondants],axis='columns')
python_df

,count,LanguageHaveWorkedWith
Country,,
United States of America,11095,6251
Germany,4947,2647
India,4231,2128
United Kingdom of Great Britain and Northern Ireland,3224,1638
Ukraine,2672,963
...,...,...
Central African Republic,1,1
Equatorial Guinea,1,0
Niger,1,1
Guinea,1,0
Solomon Islands,1,0

In [34]:
 #Renaming columns
python_df.rename(columns={ 'count': 'Total_Respon' , 'LanguageHaveWorkedWith' : 'Knows_Python'},inplace= True)
python_df

                                                    Total_Respon  Knows_Python
Country
United States of America                                   11095          6251
Germany                                                     4947          2647
India                                                       4231          2128
United Kingdom of Great Britain and Northern Ir...          3224          1638
Ukraine                                                     2672           963
...                                                          ...           ...
Central African Republic                                       1             1
Equatorial Guinea                                              1             0
Niger                                                          1             1
Guinea                                                         1             0
Solomon Islands                                                1             0

[185 rows x 2 columns]

In [36]:
# Calculating percentage
python_df['PerctKnowsPython'] = (python_df['Knows_Python'] / python_df[ 'Total_Respon']) * 100
python_df

,Total_Respon,Knows_Python,PerctKnowsPython
Country,,,
United States of America,11095,6251,56.340694
Germany,4947,2647,53.507176
India,4231,2128,50.295438
United Kingdom of Great Britain and Northern Ireland,3224,1638,50.806452
Ukraine,2672,963,36.040419
...,...,...,...
Central African Republic,1,1,100.000000
Equatorial Guinea,1,0,0.000000
Niger,1,1,100.000000
Guinea,1,0,0.000000
Solomon Islands,1,0,0.000000

In [37]:
# Sort results
python_df.sort_values(by='PerctKnowsPython' , ascending= False, inplace=True)

In [39]:
python_df.head(50)

                                  Total_Respon  Knows_Python  PerctKnowsPython
Country
Niger                                        1             1        100.000000
Central African Republic                     1             1        100.000000
Samoa                                        1             1        100.000000
Lesotho                                      1             1        100.000000
Saint Kitts and Nevis                        1             1        100.000000
Dominica                                     1             1        100.000000
Chad                                         1             1        100.000000
Belize                                       2             2        100.000000
Brunei Darussalam                            3             3        100.000000
Mauritania                                   5             4         80.000000
Liberia                                      4             3         75.000000
Congo, Republic of the...                    8             6         75.000000
Libyan Arab Jamahiriya                       4             3         75.000000
Guyana                                       3             2         66.666667
Sierra Leone                                 3             2         66.666667
North Korea                                  3             2         66.666667
Democratic Republic of the Congo             3             2         66.666667
Monaco                                       3             2         66.666667
Bhutan                                       3             2         66.666667
Zimbabwe                                    26            17         65.384615
El Salvador                                 19            12         63.157895
Kuwait                                       8             5         62.500000
Singapore                                  177           110         62.146893
Israel                                     604           360         59.602649
South Korea                                146            87         59.589041
Rwanda                                      22            13         59.090909
Uganda                                      39            23         58.974359
Kenya                                      180           106         58.888889
Morocco                                     98            57         58.163265
Iceland                                     31            18         58.064516
Japan                                      288           167         57.986111
Chile                                      133            77         57.894737
China                                      406           233         57.389163
Mozambique                                   7             4         57.142857
Tajikistan                                   7             4         57.142857
Sudan                                        7             4         57.142857
United States of America                 11095          6251         56.340694
France                                    2110          1187         56.255924
Maldives                                    16             9         56.250000
Yemen                                       18            10         55.555556
Luxembourg                                  40            22         55.000000
Turkmenistan                                11             6         54.545455
Ireland                                    270           147         54.444444
Guatemala                                   41            22         53.658537
Finland                                    386           207         53.626943
Germany                                   4947          2647         53.507176
Sri Lanka                                  163            87         53.374233
Andorra                                     15             8         53.333333
Zambia                                      15             8         53.333333
Canada                                    2104          1120         53.231939

In [40]:
# For particular country
python_df.loc['India']

Total_Respon        4231.000000
Knows_Python        2128.000000
PerctKnowsPython      50.295438
Name: India, dtype: float64