In [29]:
import pandas as pd

In [32]:

df = pd.read_csv('Bitcoin_data.csv')

In [39]:
df

           Date     Price      Open      High       Low    Vol. Change %
0    2024-02-09  47,545.4  45,293.3  47,710.2  45,254.2  86.85K    4.97%
1    2024-02-08  45,293.3  44,346.2  45,579.2  44,336.4  66.38K    2.15%
2    2024-02-07  44,339.8  43,088.4  44,367.9  42,783.5  48.57K    2.91%
3    2024-02-06  43,087.7  42,697.6  43,375.5  42,566.8  33.32K    0.91%
4    2024-02-05  42,697.2  42,581.4  43,532.2  42,272.5  39.26K    0.27%
...         ...       ...       ...       ...       ...     ...      ...
4950 2010-07-22       0.1       0.1       0.1       0.1   2.16K    0.00%
4951 2010-07-21       0.1       0.1       0.1       0.1   0.58K    0.00%
4952 2010-07-20       0.1       0.1       0.1       0.1   0.26K    0.00%
4953 2010-07-19       0.1       0.1       0.1       0.1   0.57K    0.00%
4954 2010-07-18       0.1       0.0       0.1       0.1   0.08K    0.00%

[4955 rows x 7 columns]

In [40]:
df.shape

(4955, 7)

Convert strg to date format

In [41]:
df['Date'] = pd.to_datetime(df['Date'], format='%b %d, %Y')

In [42]:
df.loc[0,'Date'].day_name()

'Friday'

In [43]:
# Date method on entire series
df['Date'].dt.day_name()

0          Friday
1        Thursday
2       Wednesday
3         Tuesday
4          Monday
          ...
4950     Thursday
4951    Wednesday
4952      Tuesday
4953       Monday
4954       Sunday
Name: Date, Length: 4955, dtype: object

In [44]:
# Creating new column from date
df['DayOfWeek'] = df['Date'].dt.day_name()

In [45]:
df

,Date,Price,Open,High,Low,Vol.,Change %,DayOfWeek
0,2024-02-09,"47,545.4","45,293.3","47,710.2","45,254.2",86.85K,4.97%,Friday
1,2024-02-08,"45,293.3","44,346.2","45,579.2","44,336.4",66.38K,2.15%,Thursday
2,2024-02-07,"44,339.8","43,088.4","44,367.9","42,783.5",48.57K,2.91%,Wednesday
3,2024-02-06,"43,087.7","42,697.6","43,375.5","42,566.8",33.32K,0.91%,Tuesday
4,2024-02-05,"42,697.2","42,581.4","43,532.2","42,272.5",39.26K,0.27%,Monday
...,...,...,...,...,...,...,...,...
4950,2010-07-22,0.1,0.1,0.1,0.1,2.16K,0.00%,Thursday
4951,2010-07-21,0.1,0.1,0.1,0.1,0.58K,0.00%,Wednesday
4952,2010-07-20,0.1,0.1,0.1,0.1,0.26K,0.00%,Tuesday
4953,2010-07-19,0.1,0.1,0.1,0.1,0.57K,0.00%,Monday
4954,2010-07-18,0.1,0.0,0.1,0.1,0.08K,0.00%,Sunday

Earliest and most recent dates

In [46]:
df['Date'].min()

Timestamp('2010-07-18 00:00:00')

In [47]:
df['Date'].max()

Timestamp('2024-02-09 00:00:00')

In [48]:
#TIME DELTA
df['Date'].max() - df['Date'].min()

Timedelta('4954 days 00:00:00')

Filtering by date

In [54]:
filt = (df['Date'] >= '2023') & (df['Date'] < '2024')
df.loc[filt]

,Date,Price,Open,High,Low,Vol.,Change %,DayOfWeek
40,2023-12-31,"42,272.5","42,141.6","42,878.8","41,971.4",35.58K,0.32%,Sunday
41,2023-12-30,"42,136.7","42,074.7","42,592.2","41,527.3",35.18K,0.15%,Saturday
42,2023-12-29,"42,072.4","42,581.1","43,108.0","41,459.0",60.98K,-1.19%,Friday
43,2023-12-28,"42,581.1","43,446.5","43,782.6","42,309.3",49.84K,-1.99%,Thursday
44,2023-12-27,"43,446.5","42,514.3","43,676.7","42,115.3",50.10K,2.20%,Wednesday
...,...,...,...,...,...,...,...,...
400,2023-01-05,"16,829.8","16,852.2","16,877.9","16,772.3",178.96K,-0.13%,Thursday
401,2023-01-04,"16,852.1","16,674.2","16,976.5","16,656.5",247.39K,1.07%,Wednesday
402,2023-01-03,"16,674.2","16,673.1","16,773.2","16,607.2",178.73K,-0.00%,Tuesday
403,2023-01-02,"16,674.3","16,618.4","16,766.9","16,551.0",136.03K,0.34%,Monday
404,2023-01-01,"16,618.4","16,537.5","16,621.9","16,499.7",107.84K,0.49%,Sunday

In [58]:
filt1 = (df['Date'] >= pd.to_datetime('2023')) & (df['Date'] < pd.to_datetime('2024'))
df.loc[filt1]

,Date,Price,Open,High,Low,Vol.,Change %,DayOfWeek
40,2023-12-31,"42,272.5","42,141.6","42,878.8","41,971.4",35.58K,0.32%,Sunday
41,2023-12-30,"42,136.7","42,074.7","42,592.2","41,527.3",35.18K,0.15%,Saturday
42,2023-12-29,"42,072.4","42,581.1","43,108.0","41,459.0",60.98K,-1.19%,Friday
43,2023-12-28,"42,581.1","43,446.5","43,782.6","42,309.3",49.84K,-1.99%,Thursday
44,2023-12-27,"43,446.5","42,514.3","43,676.7","42,115.3",50.10K,2.20%,Wednesday
...,...,...,...,...,...,...,...,...
400,2023-01-05,"16,829.8","16,852.2","16,877.9","16,772.3",178.96K,-0.13%,Thursday
401,2023-01-04,"16,852.1","16,674.2","16,976.5","16,656.5",247.39K,1.07%,Wednesday
402,2023-01-03,"16,674.2","16,673.1","16,773.2","16,607.2",178.73K,-0.00%,Tuesday
403,2023-01-02,"16,674.3","16,618.4","16,766.9","16,551.0",136.03K,0.34%,Monday
404,2023-01-01,"16,618.4","16,537.5","16,621.9","16,499.7",107.84K,0.49%,Sunday

In [59]:
# set index to date
df.set_index('Date', inplace=True)

In [62]:
df

               Price      Open      High       Low    Vol. Change %  DayOfWeek
Date
2024-02-09  47,545.4  45,293.3  47,710.2  45,254.2  86.85K    4.97%     Friday
2024-02-08  45,293.3  44,346.2  45,579.2  44,336.4  66.38K    2.15%   Thursday
2024-02-07  44,339.8  43,088.4  44,367.9  42,783.5  48.57K    2.91%  Wednesday
2024-02-06  43,087.7  42,697.6  43,375.5  42,566.8  33.32K    0.91%    Tuesday
2024-02-05  42,697.2  42,581.4  43,532.2  42,272.5  39.26K    0.27%     Monday
...              ...       ...       ...       ...     ...      ...        ...
2010-07-22       0.1       0.1       0.1       0.1   2.16K    0.00%   Thursday
2010-07-21       0.1       0.1       0.1       0.1   0.58K    0.00%  Wednesday
2010-07-20       0.1       0.1       0.1       0.1   0.26K    0.00%    Tuesday
2010-07-19       0.1       0.1       0.1       0.1   0.57K    0.00%     Monday
2010-07-18       0.1       0.0       0.1       0.1   0.08K    0.00%     Sunday

[4955 rows x 7 columns]

In [ ]:
df.loc['2021']     # returns index/date selection
# df['2024']     column selection

,Price,Open,High,Low,Vol.,Change %,DayOfWeek
Date,,,,,,,
2021-12-31,"46,219.5","47,123.3","48,553.9","45,693.6",58.18K,-1.92%,Friday
2021-12-30,"47,123.3","46,470.7","47,901.4","46,003.0",60.96K,1.42%,Thursday
2021-12-29,"46,461.7","47,548.4","48,121.7","46,127.8",63.92K,-2.28%,Wednesday
2021-12-28,"47,545.2","50,703.4","50,703.8","47,345.7",74.39K,-6.18%,Tuesday
2021-12-27,"50,678.2","50,783.6","52,016.3","50,459.0",43.90K,-0.20%,Monday
...,...,...,...,...,...,...,...
2021-01-05,"33,991.5","32,015.4","34,414.7","30,010.5",202.13K,6.15%,Tuesday
2021-01-04,"32,022.6","33,016.6","33,587.5","28,204.5",255.27K,-2.84%,Monday
2021-01-03,"32,958.9","32,192.9","34,755.9","32,029.6",155.21K,2.38%,Sunday
2021-01-02,"32,193.3","29,359.7","33,233.5","29,008.0",240.87K,9.65%,Saturday
2021-01-01,"29,359.9","28,951.7","29,627.1","28,712.4",100.90K,1.42%,Friday

Slicing dates

In [69]:
df.index.is_monotonic_increasing

False

In [70]:
df.sort_index(inplace=True)

In [72]:
df.loc['2021-01-02' : '2021-08-02']

,Price,Open,High,Low,Vol.,Change %,DayOfWeek
Date,,,,,,,
2021-01-02,"32,193.3","29,359.7","33,233.5","29,008.0",240.87K,9.65%,Saturday
2021-01-03,"32,958.9","32,192.9","34,755.9","32,029.6",155.21K,2.38%,Sunday
2021-01-04,"32,022.6","33,016.6","33,587.5","28,204.5",255.27K,-2.84%,Monday
2021-01-05,"33,991.5","32,015.4","34,414.7","30,010.5",202.13K,6.15%,Tuesday
2021-01-06,"36,793.2","33,999.3","36,934.8","33,408.3",227.56K,8.24%,Wednesday
...,...,...,...,...,...,...,...
2021-07-29,"40,001.4","40,009.0","40,630.7","39,340.8",75.30K,-0.00%,Thursday
2021-07-30,"42,203.4","40,001.1","42,264.4","38,358.4",98.45K,5.50%,Friday
2021-07-31,"41,553.7","42,201.4","42,285.3","41,066.4",44.65K,-1.54%,Saturday
2021-08-01,"39,878.3","41,510.0","42,565.0","39,556.5",80.33K,-4.03%,Sunday
2021-08-02,"39,168.4","39,869.8","40,449.0","38,692.5",74.81K,-1.78%,Monday

In [78]:
cols = ['Open','High','Low','Price']

df[cols] = df[cols].replace(',', '', regex=True).astype(float)

In [79]:
#Avg open for Jan 2023 to Feb 2024
df.loc['2022-01-02' : '2023-02-02']['Open'].mean()

np.float64(27554.533249370274)

Resample data

In [81]:
#resample 1 column
df['High'].resample('W').max()

Date
2010-07-18        0.1
2010-07-25        0.1
2010-08-01        0.1
2010-08-08        0.1
2010-08-15        0.1
               ...
2024-01-14    48923.7
2024-01-21    43563.7
2024-01-28    42817.1
2024-02-04    43817.9
2024-02-11    47710.2
Freq: W-SUN, Name: High, Length: 709, dtype: float64

In [82]:
#Resample multiple columns
df.resample('W').agg({'High': 'max', 'Low': 'min', 'Open':'mean'})

               High      Low          Open
Date
2010-07-18      0.1      0.1      0.000000
2010-07-25      0.1      0.1      0.100000
2010-08-01      0.1      0.1      0.100000
2010-08-08      0.1      0.1      0.100000
2010-08-15      0.1      0.1      0.100000
...             ...      ...           ...
2024-01-14  48923.7  41739.6  45095.828571
2024-01-21  43563.7  40305.4  42114.600000
2024-01-28  42817.1  38546.9  40712.557143
2024-02-04  43817.9  41824.7  42877.942857
2024-02-11  47710.2  42272.5  43601.380000

[709 rows x 3 columns]