In [1]:
import pandas as pd
import numpy as np

In [2]:
#Dictionary with multiple values in key using list
person = {
    "First_Name" : ["Aditi", "Joe", "Anu", np.nan, None, "Missing"],
    "Last_Name" : ["Shaktawat", "Sin", "Dat",np.nan,np.nan,"N/A"],
    "Email" : ["abc@email.com", "av@email.com", "fgees@email.com","N/A",None, "Missing"],
    "Age": [34,12,67,np.nan, "Missing", None]}

In [3]:
df = pd.DataFrame(person)
df

  First_Name  Last_Name            Email      Age
0      Aditi  Shaktawat    abc@email.com       34
1        Joe        Sin     av@email.com       12
2        Anu        Dat  fgees@email.com       67
3        NaN        NaN              N/A      NaN
4       None        NaN             None  Missing
5    Missing        N/A          Missing     None

Handling Null Values
1. Remove null values

In [4]:
df.dropna()

  First_Name  Last_Name            Email Age
0      Aditi  Shaktawat    abc@email.com  34
1        Joe        Sin     av@email.com  12
2        Anu        Dat  fgees@email.com  67

In [5]:
df.dropna(axis='index', how='all')    #if all rows null, only them remove them

  First_Name  Last_Name            Email      Age
0      Aditi  Shaktawat    abc@email.com       34
1        Joe        Sin     av@email.com       12
2        Anu        Dat  fgees@email.com       67
3        NaN        NaN              N/A      NaN
4       None        NaN             None  Missing
5    Missing        N/A          Missing     None

In [6]:
df.dropna(axis='columns',how='any')   # removes columns which have any value in the column as null

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

In [7]:
df.dropna(axis='columns', how='all')   #only if all values in column are empty

  First_Name  Last_Name            Email      Age
0      Aditi  Shaktawat    abc@email.com       34
1        Joe        Sin     av@email.com       12
2        Anu        Dat  fgees@email.com       67
3        NaN        NaN              N/A      NaN
4       None        NaN             None  Missing
5    Missing        N/A          Missing     None

In [8]:
# If either 'Last name' or 'email' present , dont remove those values
 #  OR
# Remove rows which dont have email or last name

df.dropna(axis='index',how='any',subset=['Email','Last_Name'])

  First_Name  Last_Name            Email   Age
0      Aditi  Shaktawat    abc@email.com    34
1        Joe        Sin     av@email.com    12
2        Anu        Dat  fgees@email.com    67
5    Missing        N/A          Missing  None

In [9]:
df.isna()

   First_Name  Last_Name  Email    Age
0       False      False  False  False
1       False      False  False  False
2       False      False  False  False
3        True       True  False   True
4        True       True   True  False
5       False      False  False   True

2. Remove custom missing values

In [10]:
df.replace('N/A',np.nan,inplace=True)
df.replace('Missing',np.nan,inplace=True)
df

C:\Users\aditi\AppData\Local\Temp\ipykernel_11080\1077522833.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('Missing',np.nan,inplace=True)

  First_Name  Last_Name            Email   Age
0      Aditi  Shaktawat    abc@email.com  34.0
1        Joe        Sin     av@email.com  12.0
2        Anu        Dat  fgees@email.com  67.0
3        NaN        NaN              NaN   NaN
4       None        NaN             None   NaN
5        NaN        NaN              NaN   NaN

3. Filling Null with some different values

In [11]:
df.fillna("Not-Present")

    First_Name    Last_Name            Email          Age
0        Aditi    Shaktawat    abc@email.com         34.0
1          Joe          Sin     av@email.com         12.0
2          Anu          Dat  fgees@email.com         67.0
3  Not-Present  Not-Present      Not-Present  Not-Present
4  Not-Present  Not-Present      Not-Present  Not-Present
5  Not-Present  Not-Present      Not-Present  Not-Present

In [12]:
df['Age'].fillna(0)

0    34.0
1    12.0
2    67.0
3     0.0
4     0.0
5     0.0
Name: Age, dtype: float64

Casting datatypes

In [13]:
df.dtypes

First_Name     object
Last_Name      object
Email          object
Age           float64
dtype: object

In [14]:
df['Age'] = df['Age'].astype(float)    # can convert str to float but not to int, if missing values are present

In [15]:
df.dtypes

First_Name     object
Last_Name      object
Email          object
Age           float64
dtype: object

In [16]:
df['Age'].mean()

np.float64(37.666666666666664)