PANDAS

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('survey_dataset.csv', index_col= 'ResponseId')

In [4]:
df

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,API document(s) and/or SDK document(s);AI-powe...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#to see first 5 values
df.head()

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [6]:
#see last 5 rows
df.tail()

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,API document(s) and/or SDK document(s);AI-powe...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.shape

(65437, 113)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 65437 entries, 1 to 65437
Columns: 113 entries, MainBranch to JobSat
dtypes: float64(13), object(100)
memory usage: 56.9+ MB

In [9]:
#  df.dtypes

In [10]:
#to see all the columns
pd.set_option('display.max_columns',114)

# to see all rows
pd.set_option('display.max_rows',114)

In [11]:
#ALL columns
df.columns

Index(['MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'TechDoc',
       ...
       'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9',
       'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase',
       'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=113)

In [12]:
#Selecting a particular column
df['Employment']

ResponseId
1        Employed, full-time
2        Employed, full-time
3        Employed, full-time
4         Student, full-time
5         Student, full-time
                ...
65433    Employed, full-time
65434    Employed, full-time
65435    Employed, full-time
65436    Employed, full-time
65437     Student, full-time
Name: Employment, Length: 65437, dtype: object

In [13]:
#Count values of a particular column
df['Age'].value_counts()

Age
25-34 years old       23911
35-44 years old       14942
18-24 years old       14098
45-54 years old        6249
55-64 years old        2575
Under 18 years old     2568
65 years or older       772
Prefer not to say       322
Name: count, dtype: int64

Selecting rows

In [14]:
df.loc[1]   #Returns row of 1st index ie. 2nd row

MainBranch                                           I am a developer by profession
Age                                                              Under 18 years old
Employment                                                      Employed, full-time
RemoteWork                                                                   Remote
Check                                                                        Apples
CodingActivities                                                              Hobby
EdLevel                                                   Primary/elementary school
LearnCode                                                    Books / Physical media
LearnCodeOnline                                                                 NaN
TechDoc                                                                         NaN
YearsCode                                                                       NaN
YearsCodePro                                                                    NaN
DevType                                                                         NaN
OrgSize                                                                         NaN
PurchaseInfluence                                                               NaN
BuyNewTool                                                                      NaN
BuildvsBuy                                                                      NaN
TechEndorse                                                                     NaN
Country                                                    United States of America
Currency                                                                        NaN
CompTotal                                                                       NaN
LanguageHaveWorkedWith                                                          NaN
LanguageWantToWorkWith                                                          NaN
LanguageAdmired                                                                 NaN
DatabaseHaveWorkedWith                                                          NaN
DatabaseWantToWorkWith                                                          NaN
DatabaseAdmired                                                                 NaN
PlatformHaveWorkedWith                                                          NaN
PlatformWantToWorkWith                                                          NaN
PlatformAdmired                                                                 NaN
WebframeHaveWorkedWith                                                          NaN
WebframeWantToWorkWith                                                          NaN
WebframeAdmired                                                                 NaN
EmbeddedHaveWorkedWith                                                          NaN
EmbeddedWantToWorkWith                                                          NaN
EmbeddedAdmired                                                                 NaN
MiscTechHaveWorkedWith                                                          NaN
MiscTechWantToWorkWith                                                          NaN
MiscTechAdmired                                                                 NaN
ToolsTechHaveWorkedWith                                                         NaN
ToolsTechWantToWorkWith                                                         NaN
ToolsTechAdmired                                                                NaN
NEWCollabToolsHaveWorkedWith                                                    NaN
NEWCollabToolsWantToWorkWith                                                    NaN
NEWCollabToolsAdmired                                                           NaN
OpSysPersonal use                                                               NaN
OpSysProfessional use                                                           NaN
OfficeStackAsyncHaveWorkedWith                                                  NaN
OfficeStackAsyncWantToWorkWith                                                  NaN
OfficeStackAsyncAdmired                                                         NaN
OfficeStackSyncHaveWorkedWith                                                   NaN
OfficeStackSyncWantToWorkWith                                                   NaN
OfficeStackSyncAdmired                                                          NaN
AISearchDevHaveWorkedWith                                                       NaN
AISearchDevWantToWorkWith                                                       NaN
AISearchDevAdmired                                                              NaN
NEWSOSites                        I have never visited Stack Overflow or the Sta...
SOVisitFreq                                                                     NaN
SOAccount                                                                       NaN
SOPartFreq                                                                      NaN
SOHow                                                                           NaN
SOComm                                                                          NaN
AISelect                                                                        Yes
AISent                                                               Very favorable
AIBen                                                         Increase productivity
AIAcc                                                                           NaN
AIComplex                                                                       NaN
AIToolCurrently Using                                                           NaN
AIToolInterested in Using                                                       NaN
AIToolNot interested in Using                                                   NaN
AINextMuch more integrated                                                      NaN
AINextNo change                                                                 NaN
AINextMore integrated                                                           NaN
AINextLess integrated                                                           NaN
AINextMuch less integrated                                                      NaN
AIThreat                                                                        NaN
AIEthics                                                                        NaN
AIChallenges                                                                    NaN
TBranch                                                                          No
ICorPM                                                                          NaN
WorkExp                                                                         NaN
Knowledge_1                                                                     NaN
Knowledge_2                                                                     NaN
Knowledge_3                                                                     NaN
Knowledge_4                                                                     NaN
Knowledge_5                                                                     NaN
Knowledge_6                                                                     NaN
Knowledge_7                                                                     NaN
Knowledge_8                                                                     NaN
Knowledge_9                                                                     NaN
Frequency_1                                                                     NaN
Frequency_2                                                                     NaN
Frequency_3                                                                     NaN
TimeSearching                                                                   NaN
TimeAnswering                                                                   NaN
Frustration                                                                     NaN
ProfessionalTech                                                                NaN
ProfessionalCloud                                                               NaN
ProfessionalQuestion                                                            NaN
Industry                                                                        NaN
JobSatPoints_1                                                                  NaN
JobSatPoints_4                                                                  NaN
JobSatPoints_5                                                                  NaN
JobSatPoints_6                                                                  NaN
JobSatPoints_7                                                                  NaN
JobSatPoints_8                                                                  NaN
JobSatPoints_9                                                                  NaN
JobSatPoints_10                                                                 NaN
JobSatPoints_11                                                                 NaN
SurveyLength                                                                    NaN
SurveyEase                                                                      NaN
ConvertedCompYearly                                                             NaN
JobSat                                                                          NaN
Name: 1, dtype: object

In [15]:
# Select rows of particular columns
df.loc[[1,2], ['Age', 'Employment', 'EdLevel']]

,Age,Employment,EdLevel
ResponseId,,,
1,Under 18 years old,"Employed, full-time",Primary/elementary school
2,35-44 years old,"Employed, full-time","Bachelor’s degree (B.A., B.S., B.Eng., etc.)"

In [16]:
#SLICING -
# loc- last index inclusive
df.loc[1:4, 'Age' :'CodingActivities']

,Age,Employment,RemoteWork,Check,CodingActivities
ResponseId,,,,,
1,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby
2,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...
3,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...
4,18-24 years old,"Student, full-time",NaN,Apples,NaN

INDEXING

In [17]:
df.index

Index([    1,     2,     3,     4,     5,     6,     7,     8,     9,    10,
       ...
       65428, 65429, 65430, 65431, 65432, 65433, 65434, 65435, 65436, 65437],
      dtype='int64', name='ResponseId', length=65437)

In [18]:
df.sort_index(inplace= True)

Filtering

In [19]:
# Return age, country, years exp where exp is greater than 10 years
years_exp = (df['YearsCode'] > '10')
df.loc[years_exp, ['YearsCode', 'Age' ,'Country']]

,YearsCode,Age,Country
ResponseId,,,
2,20,35-44 years old,United Kingdom of Great Britain and Northern I...
3,37,45-54 years old,United Kingdom of Great Britain and Northern I...
4,4,18-24 years old,Canada
5,9,18-24 years old,Norway
7,7,35-44 years old,United States of America
...,...,...,...
65429,4,25-34 years old,India
65432,38,45-54 years old,Belgium
65433,5,18-24 years old,NaN
65435,9,25-34 years old,NaN
65436,5,18-24 years old,Germany

In [20]:
lang_known = df['LanguageHaveWorkedWith'] == 'Python'
df.loc[lang_known, 'LanguageHaveWorkedWith']

ResponseId
38       Python
58       Python
91       Python
170      Python
201      Python
          ...
64965    Python
65007    Python
65122    Python
65329    Python
65343    Python
Name: LanguageHaveWorkedWith, Length: 832, dtype: object

In [21]:
# If countries in list, return age
Countries = ['India', 'Belgium','Germany', 'UK']
filt = df['Country'].isin(Countries)
df.loc[filt,'Country']

ResponseId
18         India
19       Germany
21       Germany
22       Germany
49       Germany
          ...
65414      India
65416      India
65429      India
65432    Belgium
65436    Germany
Name: Country, Length: 9704, dtype: object

In [22]:
# String Operations

#Filter where lang known has 'python' present in them

lang_present = df['LanguageHaveWorkedWith'].str.contains('Python', na=False)
df.loc[lang_present, 'LanguageHaveWorkedWith']

ResponseId
2        Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...
4        C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...
5                  C++;HTML/CSS;JavaScript;Lua;Python;Rust
6        Bash/Shell (all shells);HTML/CSS;Java;JavaScri...
11                                  JavaScript;Python;Ruby
                               ...
65422                       Bash/Shell (all shells);Python
65428                                    MATLAB;Python;SQL
65432    Bash/Shell (all shells);C;C#;C++;Delphi;Groovy...
65436             C;C++;Go;Lua;Objective-C;Python;Rust;SQL
65437     C;HTML/CSS;Java;JavaScript;PHP;Python;TypeScript
Name: LanguageHaveWorkedWith, Length: 30795, dtype: object

Changing Column names

In [26]:
df['YearsCode'].head(10)
# df.head (10)

ResponseId
1     NaN
2      20
3      37
4       4
5       9
6      10
7       7
8       1
9      20
10     15
Name: YearsCode, dtype: object

In [29]:
df.rename(columns={ 'YearsCode': 'CodingExp'}, inplace=True)

In [30]:
df['CodingExp']

ResponseId
1        NaN
2         20
3         37
4          4
5          9
        ...
65433      5
65434    NaN
65435      9
65436      5
65437    NaN
Name: CodingExp, Length: 65437, dtype: object

Changing case of columns

In [32]:
df.columns = df.columns.str.lower()
df

,mainbranch,age,employment,remotework,check,codingactivities,edlevel,learncode,learncodeonline,techdoc,codingexp,yearscodepro,devtype,orgsize,purchaseinfluence,buynewtool,buildvsbuy,techendorse,country,currency,comptotal,languagehaveworkedwith,languagewanttoworkwith,languageadmired,databasehaveworkedwith,databasewanttoworkwith,databaseadmired,platformhaveworkedwith,platformwanttoworkwith,platformadmired,webframehaveworkedwith,webframewanttoworkwith,webframeadmired,embeddedhaveworkedwith,embeddedwanttoworkwith,embeddedadmired,misctechhaveworkedwith,misctechwanttoworkwith,misctechadmired,toolstechhaveworkedwith,toolstechwanttoworkwith,toolstechadmired,newcollabtoolshaveworkedwith,newcollabtoolswanttoworkwith,newcollabtoolsadmired,opsyspersonal use,opsysprofessional use,officestackasynchaveworkedwith,officestackasyncwanttoworkwith,officestackasyncadmired,officestacksynchaveworkedwith,officestacksyncwanttoworkwith,officestacksyncadmired,aisearchdevhaveworkedwith,aisearchdevwanttoworkwith,aisearchdevadmired,newsosites,sovisitfreq,soaccount,sopartfreq,sohow,socomm,aiselect,aisent,aiben,aiacc,aicomplex,aitoolcurrently using,aitoolinterested in using,aitoolnot interested in using,ainextmuch more integrated,ainextno change,ainextmore integrated,ainextless integrated,ainextmuch less integrated,aithreat,aiethics,aichallenges,tbranch,icorpm,workexp,knowledge_1,knowledge_2,knowledge_3,knowledge_4,knowledge_5,knowledge_6,knowledge_7,knowledge_8,knowledge_9,frequency_1,frequency_2,frequency_3,timesearching,timeanswering,frustration,professionaltech,professionalcloud,professionalquestion,industry,jobsatpoints_1,jobsatpoints_4,jobsatpoints_5,jobsatpoints_6,jobsatpoints_7,jobsatpoints_8,jobsatpoints_9,jobsatpoints_10,jobsatpoints_11,surveylength,surveyease,convertedcompyearly,jobsat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,NaN,Yes,Very favorable,Increase productivity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.0,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,4,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Canada,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,HTML/CSS;Java;JavaScript;PowerShell;Python;SQL...,MongoDB;MySQL;PostgreSQL;SQLite,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Fly.io;Heroku,Amazon Web Services (AWS);Vercel,Amazon Web Services (AWS),jQuery;Next.js;Node.js;React;WordPress,jQuery;Next.js;Node.js;React,jQuery;Next.js;Node.js;React,Rasberry Pi,NaN,NaN,NumPy;Pandas;Ruff;TensorFlow,NaN,NaN,Docker;npm;Pip,Docker;Kubernetes;npm,Docker;npm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,No,NaN,Quickly finding code solutions,"No, not really",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,Testing code;Committing and reviewing code;Pre...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don’t trust the output or answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,9,NaN,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Norway,NaN,NaN,C++;HTML/CSS;JavaScript;Lua;Python;Rust,C++;HTML/CSS;JavaScript;Lua;Python,C++;HTML/CSS;JavaScript;Lua;Python,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,NaN,NaN,NaN,CMake;Cargo;Rasberry Pi,CMake;Rasberry Pi,CMake;Rasberry Pi,NaN,NaN,NaN,APT;Make;npm,APT;Make,APT;Make,Vim,Vim,Vim,Other (please specify):,NaN,GitHub Discussions;Markdown File;Obsidian;Stac...,GitHub Discussions;Markdown File;Obsidian,GitHub Discussions;Markdown File;Obsidian,Discord;Whatsapp,Discord;Whatsapp,Discord;Whatsapp,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,NaN,5,3,Blockchain,2 to 9 employees,I have some influence,Ask developers I know/work with;Ask a generati...,Is ready-to-go but also customizable for growt...,APIs;Integrated developer community;Quality su...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Favorable,Increase productivity;Greater efficiency;Speed...,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Project planning;Wri...,Debugging and getting help;Testing code;Deploy...,Committing and reviewing code,Writing code;Search for answers;Generating con...,NaN,Learning about a codebase;Project planning;Doc...,NaN,NaN,No,Circulating misinformation or disinformation,"AI tools lack context of codebase, internal a...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,API document(s) and/or SDK document(s);AI-powe...,9,5,"Developer, mobile","1,000 to 4,999 employees",I have little or no influence,Ask developers I know/work with;Ask a generati...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,5,2,"Developer, back-end",20 to 99 employees,I have some influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Connected to an open source...,Germany,EUR European Euro,NaN,C;C++;Go;Lua;Objective-C;Python;Rust;SQL,Rust;SQL,Rust;SQL,PostgreSQL;SQLite,PostgreSQL;SQLite,PostgreSQL;SQLite,NaN,NaN,NaN,Angular;Node.js;React,NaN,NaN,Arduino;CMake;Cargo;GNU GCC;Rasberry Pi,Cargo;GNU GCC;Rasberry Pi,Cargo;GNU GCC;Rasberry Pi,GTK;OpenGL,NaN,NaN,Ansible;APT;Docker;Make;npm;Pip;Podman,Ansible;APT;Docker;Make;npm;Pip;Podman,Ansible;APT;Docker;Make;npm;Pip;Podman,Vim;Visual Studio Code,Vim;Visual Studio Code,Vim;Visual Studio Code,Android;Other Linux-based;Ubuntu;Windows,Fedora;Other Linux-based;Ubuntu,Confluence;Jira;Markdown File;Obsidian;Trello,Confluence;Jira;Markdown File;Trello,Confluence;Jira;Markdown File;Trello,Discord;Jitsi;Microsoft Teams;Whatsapp,Discord;Jitsi;Whatsapp,Discord;Jitsi;Whatsapp,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,No,NaN,Quickly finding code solutions,"No, not really","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;HTML/CSS;Java;JavaScript;PHP;Python;TypeScript,JavaScript;Python;TypeScript,JavaScript;Python;TypeScript,MongoDB;MySQL;Oracle;PostgreSQL,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Cloudflare;Google Cl...,Cloudflare;Google Cloud;Netlify;Vercel,Cloudflare;Google Cloud;Netlify;Vercel,Django;Express;jQuery;Next.js;Node.js;React,Django;Express;Next.js;Node.js;React,Django;Express;Next.js;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Pip;Vite,npm;Pip;Vite,npm;Pip;Vite,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows,MacOS;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow,Daily or almost daily,Yes,Less than once per month or monthly,Quickly finding code solutions,"Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Changing rows values

In [ ]:
#Change the surveyease as simple for easy and hard for difficult row values
df['surveyease'].unique()

array([nan, 'Easy', 'Neither easy nor difficult', 'Difficult'],
      dtype=object)

In [ ]:
#Using map - values not changed will become Nan
df['surveyease'].map({'Easy' : 'Simple', 'Difficult':'Hard'})

ResponseId
1           NaN
2           NaN
3        Simple
4        Simple
5        Simple
          ...
65433       NaN
65434       NaN
65435       NaN
65436       NaN
65437       NaN
Name: surveyease, Length: 65437, dtype: object

In [36]:
df['surveyease'].replace({'Easy' : 'Simple', 'Difficult':'Hard'})

ResponseId
1           NaN
2           NaN
3        Simple
4        Simple
5        Simple
          ...
65433       NaN
65434       NaN
65435       NaN
65436       NaN
65437       NaN
Name: surveyease, Length: 65437, dtype: object

In [38]:
# Change to dataframe
df['surveyease'] = df['surveyease'].replace({'Easy' : 'Simple', 'Difficult':'Hard'})

In [ ]:
df['surveyease'].unique()  # new changed dataframe

array([nan, 'Simple', 'Neither easy nor difficult', 'Hard'], dtype=object)